language: python
python:
  - "2.7"
# command to install dependencies
install:
  - ./setup_environment.sh
# command to run tests

script:
  - python models/research/object_detection/builders/model_builder_test.py


